package com.garg.service;

import java.util.ArrayList;
import java.util.List;

import com.garg.model.CapitalExpenditure;
import com.garg.model.ImportantVariables;
import com.garg.model.OperatingCash;
import com.garg.model.OutputVariable;
import com.garg.model.Rate;

public class CashFlowService {

	CapitalExpenditure ce;
	OperatingCash oc;
	ImportantVariables iv;
	Rate rate;
	
	public CashFlowService(CapitalExpenditure ce,OperatingCash oc,ImportantVariables iv,Rate rate) {
		this.ce = ce;
		this.oc = oc;
		this.iv= iv;
		this.rate = rate;
	}
	
	

	public OutputVariable averageCashFlow() {
		OutputVariable ov = new OutputVariable();
		System.out.println("The future cash flow is as follows: ");

		List<Double> list = new ArrayList<>();

		for (int i = 1; i <= 5; i++) {
			double firstFiveYear = iv.getAverageNetCashFlow()
					* Math.pow((1 + (rate.getFirstFiveYearGrowthRate() / 100)), i);
			list.add(firstFiveYear);
		}

		double fifthCash = iv.getAverageNetCashFlow() * Math.pow((1 + (rate.getFirstFiveYearGrowthRate() / 100)), 5);

		for (int i = 6; i <= 10; i++) {
			double lastFiveYear = fifthCash * Math.pow((1 + (rate.getLastFiveYearGrowthRate() / 100)), i - 5);
			list.add((i - 1), lastFiveYear);
		}

		System.out.println(list);
		double tenthCash = fifthCash * Math.pow((1 + (rate.getLastFiveYearGrowthRate() / 100)), 5);

		double terminalValue = tenthCash * (1 + (rate.getTerminalGrowthRate() / 100))
				/ ((rate.getDiscountRate() - rate.getTerminalGrowthRate()) / 100);
		System.out.println("The terminal value is: " + terminalValue);
		
		double sumNpv = 0;
		for (int i = 1; i <= 10; i++) {
			double npv = list.get(i - 1) / Math.pow(1 + (rate.getDiscountRate() / 100), i);
			System.out.println("the npv of each till " + i + " is: " + npv);

			sumNpv = npv + sumNpv;
			System.out.println("NPV of future cash flow: " + sumNpv);
		}
		double terminalNpv = terminalValue / Math.pow(1 + (rate.getDiscountRate() / 100), 10);
		double shareholderCash = terminalNpv + sumNpv;
		System.out.println(
				"Standing today and looking into future ,the expected total free cash flow to be generated by company is: "
						+ shareholderCash);

		
		ov.setIntrinsicValue(
				((shareholderCash - (iv.getNetDebt() - (iv.getCashAndCashEquivalents() + iv.getBankBalance())))
						/ iv.getTotalShares()));
		System.out.println("The Intrinsic value of share is: " + ov.getIntrinsicValue());
		
		ov.setIntrinsicValueLower(ov.getIntrinsicValue() * 0.9);
		ov.setIntrinsicValueUpper(ov.getIntrinsicValue() * 1.1);

		System.out.println("The stock is fairly value between " + ov.getIntrinsicValueLower() + " and "
				+ ov.getIntrinsicValueUpper());
		ov.setConservativeIntrinsicValue(ov.getIntrinsicValueLower() * 0.7);
		System.out.println(
				"Taking 30% as margin of safety to be on conservative side: " + ov.getConservativeIntrinsicValue());

		return ov;
	}

}