package com.garg.service;

import java.util.*;

import com.garg.model.ImportantVariables;
import com.garg.model.Rate;

public class FreeCashFlowCalculation {
	Rate rate = new Rate();
	ImportantVariables iv = new ImportantVariables();
	CashFlow cf = new CashFlow();
	Scanner sc = new Scanner(System.in);

	public void FCF() {
		System.out.println("The future cash flow is as follows: ");
		
		List<Double> list = new ArrayList<>();

		for (int i = 1; i <= 5; i++) {
			double firstFiveYear = cf.averageCashFlow() * Math.pow((1 + (rate.getFirstFiveYearGrowthRate() / 100)), i);
			// System.out.println("The future cash flow for " + i + "th year is " + sum);
			list.add(firstFiveYear);
		}

		double fifthCash = iv.getAverageNetCashFlow() * Math.pow((1 + (rate.getFirstFiveYearGrowthRate() / 100)), 5);
//
		for (int i = 6; i <= 10; i++) {
			double lastFiveYear = fifthCash * Math.pow((1 + (rate.getLastFiveYearGrowthRate() / 100)), i - 5);
			// System.out.println("The future cash flow for " + i + "th year is " + sum1);
			list.add((i - 1), lastFiveYear);
		}

//		System.out.println(list);
		double tenthCash = fifthCash * Math.pow((1 + (rate.getLastFiveYearGrowthRate() / 100)), 5);
//
		double terminalValue = tenthCash * (1 + (rate.getTerminalGrowthRate() / 100))
				/ ((rate.getDiscountRate() - rate.getTerminalGrowthRate()) / 100);
		System.out.println("The terminal value is: " + terminalValue);
//
//		 calculation of npv of future cash flow
		double sumNpv = 0;
		for (int i = 1; i <= 10; i++) {
			double npv = list.get(i - 1) / Math.pow(1 + (rate.getDiscountRate() / 100), i);
			System.out.println("the npv of each till " + i + " is: " + npv);

			sumNpv = npv + sumNpv;
			System.out.println("NPV of future cash flow: " + sumNpv);
		}
		double terminalNpv = terminalValue / Math.pow(1 + (rate.getDiscountRate() / 100), 10);
		// System.out.println("The net present value of terminal value is: " +
		// terminalNpv);
		double shareholderCash = terminalNpv + sumNpv;
		System.out.println(
				"Standing today and looking into future ,the expected total free cash flow to be generated by company is: "
						+ shareholderCash);

//		totalPVOfFCF = shareholderCash - netDebt;
//		System.out.println("The total present value of Free Cash flow is: " + totalPVOfFCF);
//
		System.out.println("Enter Total Outstanding Shares Of company ");
		iv.setTotalShares(sc.nextDouble());

		System.out.println("Enter Net Debt OF company ");
		iv.setNetDebt(sc.nextDouble());

		System.out.println("Enter Total Cash & Cash Equivalents Of company ");
		iv.setCashAndCashEquivalents(sc.nextDouble());

		System.out.println("Enter Total Bank Balance Of company ");
		iv.setBankBalance(sc.nextDouble());

		iv.setIntrinsicValue(((shareholderCash - iv.getNetDebt()) / iv.getTotalShares()));
//
		System.out.println("The Intrinsic value of share is: " + iv.getIntrinsicValue());
//
//		System.out.println("Assuming 10 % error for upper and lower band, the intrinsic value will be: ");
		double intrinsicValueLower = iv.getIntrinsicValue() * 0.9;
		double intrinsicValueUpper = iv.getIntrinsicValue() * 1.1;
//
		System.out.println("The stock is fairly value between " + intrinsicValueLower + " and " + intrinsicValueUpper);
//
		System.out.println("Taking 30% as margin of safety to be on conservative side: " + intrinsicValueLower * 0.7);

		
	}
	

}
